backend:
  replicaCount: 1
  image:
    repository: autolog-backend
    tag: latest
    pullPolicy: Always
  env:
    springProfilesActive: stage
    datasourceUrl: jdbc:postgresql://REPLACE_WITH_STAGE_RDS_ENDPOINT:5432/autolog
    corsAllowedOrigins: https://stage.autolog.com.br
  secrets:
    create: false
    existingSecret: autolog-stage-backend-secrets

frontend:
  replicaCount: 1
  image:
    repository: autolog-frontend
    tag: latest
    pullPolicy: Always
  env:
    apiBaseUrl: https://api-stage.autolog.com.br

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
  frontend:
    host: stage.autolog.com.br
  backend:
    host: api-stage.autolog.com.br
