backend:
  replicaCount: 1
  image:
    repository: autolog-backend
    tag: latest
    pullPolicy: Always
  env:
    springProfilesActive: demo
    datasourceUrl: jdbc:postgresql://REPLACE_WITH_DEMO_RDS_ENDPOINT:5432/autolog
    corsAllowedOrigins: https://demo.autolog.com.br
  secrets:
    create: false
    existingSecret: autolog-demo-backend-secrets

frontend:
  replicaCount: 1
  image:
    repository: autolog-frontend
    tag: latest
    pullPolicy: Always
  env:
    apiBaseUrl: https://api-demo.autolog.com.br

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: autolog-demo
  listenPorts: '[{"HTTP":80}]'
  certificateArn: ""
  https:
    enabled: false
    sslRedirect: "443"
  frontend:
    host: demo.autolog.com.br
    healthcheckPath: /health
  backend:
    host: api-demo.autolog.com.br
    healthcheckPath: /actuator/health
