package com.mmetzner.vmh.shared.exception;

public enum ApiErrorCode {

    REQUEST_VALIDATION_FAILED,
    MALFORMED_REQUEST_BODY,
    DATA_INTEGRITY_CONFLICT,
    UNEXPECTED_SERVER_ERROR,
    USER_NOT_FOUND,
    USER_ALREADY_REGISTERED,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN
}