spring:
  config:
    activate:
      on-profile: demo

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

app:
  jwt:
    secret: ${JWT_SECRET}
  security:
    cors:
      allowed-origins: ${APP_SECURITY_CORS_ALLOWED_ORIGINS:https://demo.autolog.com.br}
