apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autolog.backendName" . }}-config
  labels:
    {{- include "autolog.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.backend.env.springProfilesActive | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.backend.env.datasourceUrl | quote }}
  APP_SECURITY_CORS_ALLOWED_ORIGINS: {{ .Values.backend.env.corsAllowedOrigins | quote }}
