{{- if .Values.backend.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autolog.backendSecretName" . }}
  labels:
    {{- include "autolog.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.backend.secrets.datasourceUsernameKey }}: {{ .Values.backend.secrets.datasourceUsername | quote }}
  {{ .Values.backend.secrets.datasourcePasswordKey }}: {{ .Values.backend.secrets.datasourcePassword | quote }}
  {{ .Values.backend.secrets.jwtSecretKey }}: {{ .Values.backend.secrets.jwtSecret | quote }}
{{- end }}
